Documentation:
  Enabled: false

LineLength:
  Max: 99

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'app/admin/*.rb'

Metrics/MethodLength:
  Exclude:
    - "app/controllers/api/v1/*.rb"
